# Generated by Django 5.0.6 on 2024-05-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0002_alter_employees_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='uid',
            field=models.CharField(default='3AipdM', editable=False, max_length=10, unique=True),
        ),
    ]
