# Generated by Django 5.0.6 on 2024-05-16 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0004_alter_employees_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clocking',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clockings', to='timetracker.employees'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='uid',
            field=models.CharField(default='fAQ9aK', editable=False, max_length=10, unique=True),
        ),
    ]
