# Generated by Django 5.0.6 on 2024-05-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0005_alter_clocking_employee_alter_employees_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='uid',
            field=models.CharField(default='FTUWPK', editable=False, max_length=10, unique=True),
        ),
    ]
