# Generated by Django 5.0.6 on 2024-05-17 20:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0006_alter_employees_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='uid',
            field=models.CharField(default='QP6zwU', editable=False, max_length=10, unique=True),
        ),
    ]
